name: OWASP ZAP Security Scan

on:
  schedule:
    - cron: '0 0 * * 0' # Run automatically every Sunday at midnight
  workflow_dispatch: # Allows you to manually trigger the scan from the GitHub UI

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    name: Scan live website
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'https://safemailx-ai.tech/'
          # Fails the GitHub action if severe vulnerabilities are found
          fail_action: false
          allow_issue_writing: false
          artifact_name: '' # Disable built-in upload to prevent v4 naming errors

      - name: Upload ZAP Security Report
        uses: actions/upload-artifact@v7
        with:
          name: zap-security-report
          path: |
            report_html.html
            report_md.md
